### ISSUE TITLE
Video2pose

### ISSUE THREAD

**Issue by YAYAYru** [AmitMY/pose-format#29]
Hi!
Is there function of transform video or image to file format ".pose"?
Thank

**Comment by AmitMY** [comment]
We currently either support loading [OpenPose files](https://github.com/AmitMY/pose-format/blob/master/pose_format/utils/openpose.py) or running [Mediapipe Holistic](https://github.com/AmitMY/pose-format/blob/master/pose_format/utils/holistic.py)

Easiest way to do it would be:
```
# Install the transcription packages
pip install git+git://github.com/sign-language-processing/transcription.git
# Install mediapipe
pip install mediapipe

# Get a video from remote, or use a local one
curl https://media.spreadthesign.com/video/mp4/13/93875.mp4 --output sign.mp4
# Convert video to pose file
video_to_pose -i sign.mp4 --format mediapipe -o sign.pose
```

**Comment by YAYAYru** [comment]
> We currently either support loading [OpenPose files](https://github.com/AmitMY/pose-format/blob/master/pose_format/utils/openpose.py) or running [Mediapipe Holistic](https://github.com/AmitMY/pose-format/blob/master/pose_format/utils/holistic.py)
> 
> Easiest way to do it would be:
> 
> ```shell
> # Install the transcription packages
> pip install git+git://github.com/sign-language-processing/transcription.git
> # Install mediapipe
> pip install mediapipe
> 
> # Get a video from remote, or use a local one
> curl https://media.spreadthesign.com/video/mp4/13/93875.mp4 --output sign.mp4
> # Convert video to pose file
> video_to_pose -i sign.mp4 --format mediapipe -o sign.pose
> ```
I I had this installation error:
```bash
(venv) yayay@amd2000tb:~/yayay/git/github_alien/transcription$ pip install git+git://github.com/sign-language-processing/transcription.git
Collecting git+git://github.com/sign-language-processing/transcription.git
  Cloning git://github.com/sign-language-processing/transcription.git to /tmp/pip-req-build-lzol96vo
  Running command git clone -q git://github.com/sign-language-processing/transcription.git /tmp/pip-req-build-lzol96vo
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.4]: errno=Connection timed out

ERROR: Command errored out with exit status 128: git clone -q git://github.com/sign-language-processing/transcription.git /tmp/pip-req-build-lzol96vo Check the logs for full command output.
```
But there is another way:
```bahs
git clone https://github.com/sign-language-processing/transcription.git
cd transcription
pip install .
```
Thanks for your valuable work :)

**Comment by MuhammadAasharibNawshad** [comment]
to avoid above mentioned error. 
Instead of this command
`pip install git+git://github.com/sign-language-processing/transcription.git`

use this command
`pip install git+https://github.com/sign-language-processing/transcription`
