### ISSUE TITLE
How to concatenate multiple .pose data together

### ISSUE THREAD

**Issue by fransisca25** [AmitMY/pose-format#30]
Hi, I am a beginner and have a little bit experience using mediapipe. I am still learning and try to use another system to generate data, so I have some questions: 
1. Do you have any clear examples for pose-format application?
2. I generated 1 .pose file for every video. In my case, I have 20 videos so I created 20 .pose files in total. Is there any way how to concatenate all generated .pose data like .npy files? (Because I usually use mediapipe to detect keypoints, store all keypoints data in .npy files for every frames in the video and then concatenate them all)

**Comment by bricksdont** [comment]
Hi!

To answer number 2, we don't have ready-made code to concatenate multiple `.pose` files, but I would recommend you load the pose files as `Pose` objects and then concatenate in memory.

`Pose` objects have a header and a body part. The body contains the actual pose data as a numpy array (or torch or tensorflow tensor, but numpy is the default). So what you can do is find the numpy arrays contained in each `Pose` object, concatenate them like you would any other set of numpy arrays, and then make a new `Pose` object with the result.

Here is some code off the top of my head for this:

```python
import numpy as np

from pose_format.pose import Pose
from pose_format.numpy import NumPyPoseBody

from typing import List


def read_pose_file(filepath: str) -> Pose:

    with open(filepath, "rb") as handle:
        pose = Pose.read(handle.read())

    return pose


def save_pose(pose: Pose, filepath: str):

    with open(filepath, "wb") as handle:
        pose.write(handle)


def concatenate_poses(poses: List[Pose]) -> Pose:

    header = poses[0].header
    fps = poses[0].body.fps

    numpy_arrays_data = [pose.body.data for pose in poses]
    numpy_arrays_conf = [pose.body.confidence for pose in poses]

    concatenated_data = np.concatenate(*numpy_arrays_data)
    concatenated_conf = np.concatenate(*numpy_arrays_conf)
    
    new_body = NumPyPoseBody(data=concatenated_data, confidence=concatenated_conf, fps=fps)

    return Pose(header=header, body=new_body)


def concatenate_pose_files(input_filepaths: List[str], output_filepath: str):
    
    poses = [read_pose_file(filepath) for filepath in input_filepaths]
    
    new_pose = concatenate_poses(poses)
    
    save_pose(pose=new_pose, filepath=output_filepath)
```

(I did not test this code)

**Comment by fransisca25** [comment]
Okay I got it. 
Thank you for the explaination! 
I will come back here and ask if I have another issues :)
