### ISSUE TITLE
Data normalization (skeleton scale) - couldn't find component

### ISSUE THREAD

**Issue by ShesterG** [AmitMY/pose-format#31]
Hey @AmitMY . 

Error for the Data normalization (skeleton scale) . I loaded a single frame which can be viewed at the right.
<img width="1405" alt="Screenshot 2022-10-25 at 03 28 22" src="https://user-images.githubusercontent.com/64415241/197680603-f45533a2-50ba-469a-a6a3-c6ac21615ad5.png">

**Comment by bricksdont** [comment]
Hi @ShesterG 

Please include a minimal, reproducible code example - such as a Colab link. More advice on this: https://stackoverflow.com/help/minimal-reproducible-example

Thank you

**Comment by bricksdont** [comment]
I think a reason for this might be that you have Openpose features, but apply code meant for Mediapipe Holistic, or vice versa.

**Comment by ShesterG** [comment]
Correct @bricksdont . Thank You !

**Comment by bricksdont** [comment]
Great to hear, then I'm assuming this issue can be closed?

(For future issues please remember to include reproducible code, instead of letting us guess what the problem is. Thank you!)
